### PR TITLE
Feature/daily combo

### PR DESCRIPTION
**Pull request by loockeeer**
- Add combo feature (if you do daily two days in a row, then you'll gain more in daily)
- Fix waiting time in daily
- Add a combo treshold set to 5 (after 5 days in a row, you cannot gain more)

/!\ Need to reset DAILY enmap, because this PR implies a change in daily database /!\

### CODE REVIEW

**Comment by Ayfri** [comment]
Treshold is what now ?

**Comment by loockeeer** [comment]
I kept it unchanged.
I'll consider an enhancement on 25 december

**Review by Ayfri — CHANGES_REQUESTED** [review]
Any >:(

**Comment by loockeeer** [comment]
ensurePath<T>(enmap: Enmap<any, any>, key; any, default: T, path: string): T
could become
ensurePath<T,K,V>(enmap: Enmap<K, V>, key; K, default: T, path: string): T

And that could fix the problem yes

**Comment by Ayfri** [comment]
Yes this should be better, `any` is a thing very dirty and we should avoid using it.

**Comment by loockeeer** [comment]
The problem with that solution is that it could lead to a lot of hard coded types

**Comment by Ayfri** [comment]
It's better than `any` at least ¯\_(ツ)_/¯
We can ask @CamilleAbella what he thinks ?

**Pull request merged**
